import type {
  UiConversation,
  UiMessageList,
  UiNormalizationStatus,
  UiOpportunity,
  UiStakeholderDetail,
  UiStakeholderSearchResult,
  UiTimelineEvent,
} from "./types";

export const mockNormalizationStatus: UiNormalizationStatus = {
  totalRaw: 43820,
  totalRawNormalized: 36142,
  totalRawPending: 7678,
  totalContacts: 1204,
  totalConversations: 3190,
  totalMessages: 28442,
  bySourceAccount: [
    {
      id: "mesquita-grupo",
      instanceName: "Stack360EmpresasGrupo",
      totalRaw: 18520,
      normalized: 16400,
      pending: 2120,
      normalizedPercent: 89,
    },
    {
      id: "suporte-tsm",
      instanceName: "SuporteTSM",
      totalRaw: 14300,
      normalized: 10650,
      pending: 3650,
      normalizedPercent: 74,
    },
    {
      id: "comercial",
      instanceName: "Comercial Fretes",
      totalRaw: 11000,
      normalized: 9092,
      pending: 1908,
      normalizedPercent: 83,
    },
  ],
};

export const mockStakeholders: UiStakeholderSearchResult[] = [
  {
    id: "5511998765432@s.whatsapp.net",
    name: "João Carlos Silva",
    type: "motorista",
    status: "active",
    phone: "+55 11 99876-5432",
    roles: ["Motorista", "Lead", "Multicanal"],
    channels: ["Stack360EmpresasGrupo", "SuporteTSM"],
    lastInteraction: "2026-05-15T09:41:00Z",
    totalMessages: 184,
    score: 94,
    riskScore: 18,
    confidence: 0,
    nextAction: "Completar dados",
  },
  {
    id: "5511988877777@s.whatsapp.net",
    name: "Aline Transportes ABC",
    type: "cliente",
    status: "active",
    phone: "+55 11 98887-7777",
    roles: ["Cliente", "Embarcador"],
    channels: ["Comercial Fretes"],
    lastInteraction: "2026-05-14T17:05:00Z",
    totalMessages: 96,
    score: 72,
    riskScore: 22,
    confidence: 0,
    nextAction: "Completar dados",
  },
  {
    id: "120363025555555@g.us",
    name: "Grupo Operação Sul",
    type: "grupo",
    status: "active",
    phone: "120363025555555@g.us",
    roles: ["Grupo", "Operação"],
    channels: ["Stack360EmpresasGrupo"],
    lastInteraction: "2026-05-13T13:20:00Z",
    totalMessages: 531,
    score: 61,
    riskScore: 35,
    confidence: 0,
    nextAction: "Completar dados",
  },
];

export const mockStakeholderDetail: UiStakeholderDetail = {
  ...mockStakeholders[0],
  status: "ativo",
  firstContact: "2025-11-03T12:10:00Z",
  summary:
    "Motorista com recorrência em conversas de frete e disponibilidade de veículo. Demonstra potencial para rotas longas se dados operacionais forem completados.",
  riskScore: 18,
  nextBestAction: {
    title: "Completar dados do stakeholder",
    priority: "MEDIUM",
    description: "Validar nome, empresa, papel, documento e dados operacionais.",
  },
};

export const mockConversations: UiConversation[] = [
  {
    id: "conv:5511998765432@s.whatsapp.net:mesquita",
    contactId: mockStakeholderDetail.id,
    channel: "Stack360EmpresasGrupo",
    remoteJid: "5511998765432@s.whatsapp.net",
    chatType: "individual",
    firstMessageAt: "2026-05-12T10:00:00Z",
    lastMessageAt: "2026-05-15T09:41:00Z",
    totalMessages: 128,
    subject: "Disponibilidade de carreta sider",
    lastMessage: "Resumo: interessado em rotas SP -> RJ com janela flexível.",
    status: "active",
  },
  {
    id: "conv:5511998765432@s.whatsapp.net:suporte",
    contactId: mockStakeholderDetail.id,
    channel: "SuporteTSM",
    remoteJid: "5511998765432@s.whatsapp.net",
    chatType: "individual",
    firstMessageAt: "2026-04-30T08:20:00Z",
    lastMessageAt: "2026-05-10T18:30:00Z",
    totalMessages: 56,
    subject: "Atualização cadastral",
    lastMessage: "Pendente confirmar documento e cidade base.",
    status: "pending",
  },
];

export const mockTimeline: UiTimelineEvent[] = [
  {
    id: "evt-1",
    type: "SIGNAL",
    title: "Sinal de disponibilidade",
    description: "Informou disponibilidade para cargas no corredor São Paulo e Rio de Janeiro.",
    date: "2026-05-15T09:41:00Z",
    origin: "Stack360EmpresasGrupo",
    importance: "alta",
  },
  {
    id: "evt-2",
    type: "PENDING",
    title: "Dados incompletos",
    description: "Documento, cidade base e veículo ainda precisam de confirmação.",
    date: "2026-05-14T16:00:00Z",
    origin: "Sistema",
    importance: "média",
  },
];

export const mockOpportunities: UiOpportunity[] = [
  {
    id: "opp-1",
    title: "Rota SP -> RJ",
    score: 88,
    evidence: "Mencionou disponibilidade para rota interestadual e carreta sider.",
    nextAction: "Confirmar veículo e janela de coleta",
    status: "new",
    responsible: "Comercial",
    conversationId: mockConversations[0].id,
  },
];

export const mockMessageList: UiMessageList = {
  total: 4,
  limit: 100,
  offset: 0,
  items: [
    {
      id: "msg-1",
      direction: "INBOUND",
      content: "Bom dia, tenho carreta sider disponível para amanhã.",
      type: "TEXT",
      rawType: "conversation",
      timestamp: "2026-05-15T09:35:00Z",
      contactName: "João Carlos Silva",
      status: "received",
      source: "Stack360EmpresasGrupo",
    },
    {
      id: "msg-2",
      direction: "OUTBOUND",
      content: "Consegue fazer SP para RJ com coleta no período da tarde?",
      type: "TEXT",
      rawType: "conversation",
      timestamp: "2026-05-15T09:37:00Z",
      contactName: "Operação",
      status: "sent",
      source: "Stack360EmpresasGrupo",
    },
    {
      id: "msg-3",
      direction: "INBOUND",
      content: "[sem texto extraído]",
      type: "AUDIO",
      rawType: "audioMessage",
      timestamp: "2026-05-15T09:39:00Z",
      contactName: "João Carlos Silva",
      status: "received",
      source: "Stack360EmpresasGrupo",
    },
    {
      id: "msg-4",
      direction: "INBOUND",
      content: "Faço sim, só preciso confirmar o horário da carga.",
      type: "TEXT",
      rawType: "extendedTextMessage",
      timestamp: "2026-05-15T09:41:00Z",
      contactName: "João Carlos Silva",
      status: "received",
      source: "Stack360EmpresasGrupo",
    },
  ],
};
